spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xpilot
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ENC(qBRFh37iS/C69jtJgq6ez6wWsltwIS3943M6TU0CkQIJXgacgzAVOpfDMAeAbW9RL7gIETMpo5kOyEABz1X/LSb0zOI/S1O/LUjsRa3wT3U=)
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        hibernate:
            format_sql: true
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

jasypt:
  encryptor:
    password: ${encrypt_key}