server:
  shutdown: graceful

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/xpilot
#    username: root
#    password: password
    url: ENC(beNJk8e+oa4AhM3GAo4w7J3+Cbdo5cVlWKnNiUMFO63TCZavAPd+YtGlg62ChZT9uqO4hsSvDu9P7xDA6SK9cKW9XNDaENuvAlLYrPRZ9pI=)
    username: ENC(YRWzq08be/BooojyG7eAoQ==)
    password: ENC(B5Pv+5+TCNODpB6m+h1gnUgpVQUBtmLI)
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ENC(qBRFh37iS/C69jtJgq6ez6wWsltwIS3943M6TU0CkQIJXgacgzAVOpfDMAeAbW9RL7gIETMpo5kOyEABz1X/LSb0zOI/S1O/LUjsRa3wT3U=)
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
        hibernate:
            format_sql: true

jasypt:
  encryptor:
    password: ${encrypt_key}