spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/xpilot
#    username: root
#    password: password
    url: ENC(Bet8yne5Y1L8GqxZdVf1lkquEvezuVHtHUrgA6WecGZfWZxoZLfJm8hJKL57aGrQz05cbfvaicb2Ug4mWmzQTprd7xh41UZYQjB4ltt3+RY=)
    password: ENC(hLIYUkN49b0bFWL4zfqaK3qA8oshyL9q)
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ENC(qBRFh37iS/C69jtJgq6ez6wWsltwIS3943M6TU0CkQIJXgacgzAVOpfDMAeAbW9RL7gIETMpo5kOyEABz1X/LSb0zOI/S1O/LUjsRa3wT3U=)
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
        hibernate:
            format_sql: true

jasypt:
  encryptor:
    password: ${encrypt_key}