spring:
  data:
    mongodb:
      uri: ENC(qBRFh37iS/C69jtJgq6ez6wWsltwIS3943M6TU0CkQIJXgacgzAVOpfDMAeAbW9RL7gIETMpo5kOyEABz1X/LSb0zOI/S1O/LUjsRa3wT3U=)

jasypt:
  encryptor:
    password: ${encrypt_key}

jwt:
  secret: ENC(zMPw7eJd1Zg4vQe5H9Zum3j+ndzs/1RqObZ2O+UTCjkPkI6rBcAn7+zdfKsP7KUH7hNvx1KZzoKTzQXnUZmkiCspy7Bzb0eguMnWQRRFHcaLhQFkC5S5Y7YevSZqk+3r36SMKvaFpgY=)
  access-token-validity-in-seconds: 86400 # TODO: 24 hours

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG